# Generated by Django 3.2 on 2021-05-23 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MailMagazine',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='メールマガジンID')),
                ('title', models.CharField(max_length=256, verbose_name='タイトル')),
                ('body', models.TextField(verbose_name='内容')),
                ('status', models.IntegerField(choices=[(0, '未送信'), (1, '送信済み'), (2, '送信失敗'), (3, '更新後未送信')], default=0, verbose_name='メールマガジン状態')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
            ],
            options={
                'verbose_name': 'メールマガジン',
                'verbose_name_plural': 'メールマガジン',
            },
        ),
        migrations.CreateModel(
            name='SubscribedUser',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='購読ユーザーID')),
                ('name', models.CharField(max_length=256, verbose_name='氏名')),
                ('mail_address', models.CharField(max_length=256, verbose_name='メールアドレス')),
                ('is_subscribe', models.BooleanField(default=True, verbose_name='購読状態')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
            ],
            options={
                'verbose_name': '購読ユーザー',
                'verbose_name_plural': '購読ユーザー',
            },
        ),
    ]
