# Generated by Django 3.2 on 2021-05-23 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='お問い合わせID')),
                ('name', models.CharField(max_length=256, verbose_name='氏名')),
                ('mail_address', models.CharField(max_length=256, verbose_name='メールアドレス')),
                ('content', models.TextField(verbose_name='問い合わせ内容')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='問い合わせ日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
            ],
            options={
                'verbose_name': 'お問い合わせ',
                'verbose_name_plural': 'お問い合わせ',
            },
        ),
    ]
